theme: cayman

title: Enigma Glass Documentation
description: Training materials and case studies for the Enigma Glass SIEM platform
baseurl: "/enigmaglass" # the subpath of your site, e.g. /blog
url: "https://danfred360.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty