on:
  push:
    branches:
      - main

name: CI

jobs:
  jekyll-build:
    name: Build Jekyll site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jekyll-version: [3.8.5, latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/jekyll container
      run: |
        docker run --rm \
        --volume="${{ github.workspace }}:/srv/jekyll" \
        jekyll/jekyll:${{ matrix.jekyll-version }} /bin/bash -c "gem install bundler && chmod -R 777 /srv/jekyll && bundle install && bundle exec jekyll build && bundle exec rake search:init"